[package]
name = "estradiol-soundcloud"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.215", features = ["derive"]}
ureq = { version = "2.10.1", features = ["json"]}
thiserror = "2"
regex = "1.11.1"
once_cell = "1.20.2"
